apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: <project>-dev
- apiVersion: v1
  kind: Namespace
  metadata:
    name: <project>-uat
- apiVersion: v1
  kind: Namespace
  metadata:
    name: <project>-prd
